(eval-when-compile    (require 'color-theme))
(defun color-theme-2c ()
  "Color theme by Simon Schubert, created 2011-01-24."
  (interactive)
  (color-theme-install
   '(color-theme-2c
     ((background-color . "black")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "yellow")
      (foreground-color . "lightgray")
      (mouse-color . "gray"))
     ((ac-fuzzy-cursor-color . "red")
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "black" :foreground "lightgray" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal))))
     (ac-candidate-face ((t (:background "lightgray" :foreground "black"))))
     (ac-completion-face ((t (:foreground "darkgray" :underline t))))
     (ac-gtags-candidate-face ((t (:background "lightgray" :foreground "navy"))))
     (ac-gtags-selection-face ((t (:background "navy" :foreground "black"))))
     (ac-selection-face ((t (:background "steelblue" :foreground "black"))))
     (ac-yasnippet-candidate-face ((t (:background "sandybrown" :foreground "white"))))
     (ac-yasnippet-selection-face ((t (:background "coral3" :foreground "black"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t :foreground "blue1"))))
     (completions-common-part ((t (:foreground "darkgray" :background "black"))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (nil))))
     (diff-indicator-removed ((t (:foreground "red" :background "#400000"))))
     (diff-removed ((t (:background "#400000"))))
     (diff-indicator-added ((t (:foreground "green" :background "#004000"))))
     (diff-added ((t (:background "#004000"))))
     (diff-hunk-header ((t (:foreground "yellow" :background "grey40"))))
     (escape-glyph ((t (:foreground "brown"))))
     (file-name-shadow ((t (:foreground "grey50"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (font-lock-builtin-face ((t (:foreground "yellow3"))))
     (font-lock-comment-delimiter-face ((t (:foreground "#305050" :italic t :slant italic))))
     (font-lock-comment-face ((t (:foreground "#205050" :italic t :slant italic))))
     (font-lock-constant-face ((t (:foreground "darkgreen"))))
     (font-lock-doc-face ((t (:foreground "magenta"))))
     (font-lock-function-name-face ((t (:foreground "yellow"))))
     (font-lock-keyword-face ((t (:foreground "white" :bold t :weight bold))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "blue"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "magenta4"))))
     (font-lock-type-face ((t (:foreground "green"))))
     (font-lock-variable-name-face ((t (:foreground "orange"))))
     (font-lock-warning-face ((t (:bold t :foreground "Red1" :weight bold))))
     (fringe ((t (:background "grey25"))))
     (header-line ((t (:box (:line-width -1 :style released-button) :background "grey90" :foreground "grey20" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (highlight ((t (:background "darkseagreen2"))))
     (isearch ((t (:background "yellow" :foreground "black"))))
     (isearch-fail ((t (:background "red4" :foreground "darkgray"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "#006060"))))
     (link ((t (:foreground "blue1" :underline t))))
     (link-visited ((t (:underline t :foreground "magenta4"))))
     (match ((t (:background "yellow1"))))
     (menu ((t (nil))))
     (minibuffer-prompt ((t (:foreground "#7090ff"))))
     (mode-line ((t (:background "darkred" :foreground "white" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey50" :foreground "black" :box (:line-width -1 :color "grey25" :style nil) :weight light))))
     (mouse ((t (nil))))
     (next-error ((t (:background "lightgoldenrod2"))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (popup-face ((t (:background "lightgray" :foreground "black"))))
     (popup-isearch-match ((t (:background "sky blue"))))
     (popup-menu-face ((t (:background "lightgray" :foreground "black"))))
     (popup-menu-selection-face ((t (:background "steelblue" :foreground "white"))))
     (popup-scroll-bar-background-face ((t (:background "gray"))))
     (popup-scroll-bar-foreground-face ((t (:background "black"))))
     (popup-tip-face ((t (:background "khaki1" :foreground "black"))))
     (pp^L-highlight ((t (:box (:line-width 3 :style pressed-button)))))
     (query-replace ((t (:foreground "lightskyblue1" :background "magenta3"))))
     (region ((t (:background "lightgoldenrod2"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "yellow1"))))
     (shadow ((t (:foreground "grey50"))))
     (show-paren-match ((t (:background "turquoise4"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (whitespace-empty ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-hspace ((t (:background "LemonChiffon3" :foreground "aquamarine3"))))
     (whitespace-indentation ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-line ((t (:background "gray20" :foreground "violet"))))
     (whitespace-newline ((t (:foreground "lightgray" :weight normal))))
     (whitespace-space ((t (:background "LightYellow" :foreground "aquamarine3"))))
     (whitespace-space-after-tab ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-space-before-tab ((t (:background "DarkOrange" :foreground "firebrick"))))
     (whitespace-tab ((t (:background "beige" :foreground "aquamarine3"))))
     (whitespace-trailing ((t (:bold t :background "red1" :foreground "yellow" :weight bold))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "dark green"))))
     (widget-field ((t (:background "gray85"))))
     (widget-inactive ((t (:foreground "grey50"))))
     (widget-single-line-field ((t (:background "gray85")))))))
(add-to-list 'color-themes '(color-theme-2c  "2c" "Simon Schubert"))
(provide 'color-theme-2c)
