;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        delete-horizontal-space
        electric-verilog-semi
        iedit-mode
        indent-pp-sexp
        js2-end-of-line
        jump-char-forward
        jump-char-process-char
        jump-char-repeat-backward
        kill-region-or-backward-word
        org-self-insert-command
        paredit-backward-kill-word
        paredit-comment-dwim
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-open-round
        paredit-splice-sexp
        quack-insert-closing-paren
        quack-insert-opening-paren
        save-region-or-current-line
        smart-tab
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-mode
        org-cycle
        paredit-doublequote
        smex
        universal-argument-minus
        ))
