;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	js2-end-of-line
	jump-char-forward
	jump-char-process-char
	jump-char-repeat-backward
	kill-region-or-backward-word
	paredit-comment-dwim
	paredit-forward
	paredit-forward-delete
	paredit-forward-slurp-sexp
	paredit-kill
	paredit-open-round
	paredit-splice-sexp
	save-region-or-current-line
	))

(setq mc/cmds-to-run-once
      '(
	ace-jump-mode
	smex
	universal-argument-minus
	))
