;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	js2-end-of-line
	jump-char-forward
	jump-char-process-char
	jump-char-repeat-backward
	kill-region-or-backward-word
	other-mru-window
	paredit-comment-dwim
	paredit-forward-delete
	paredit-splice-sexp
	smart-tab
	))

(setq mc/cmds-to-run-once
      '(
	ibuffer
	ido-switch-buffer
	))
